//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaenx.Creator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaenx.Creator.Properties.Messages", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string global_exception {
            get {
                return ResourceManager.GetString("global_exception", resourceCulture);
            }
        }
        
        public static string global_exception_title {
            get {
                return ResourceManager.GetString("global_exception_title", resourceCulture);
            }
        }
        
        public static string update_new {
            get {
                return ResourceManager.GetString("update_new", resourceCulture);
            }
        }
        
        public static string update_title {
            get {
                return ResourceManager.GetString("update_title", resourceCulture);
            }
        }
        
        public static string update_uptodate {
            get {
                return ResourceManager.GetString("update_uptodate", resourceCulture);
            }
        }
        
        public static string message_prompt_id {
            get {
                return ResourceManager.GetString("message_prompt_id", resourceCulture);
            }
        }
        
        public static string prompt_id {
            get {
                return ResourceManager.GetString("prompt_id", resourceCulture);
            }
        }
        
        public static string prompt_error {
            get {
                return ResourceManager.GetString("prompt_error", resourceCulture);
            }
        }
        
        public static string prompt_error_title {
            get {
                return ResourceManager.GetString("prompt_error_title", resourceCulture);
            }
        }
        
        public static string prompt_double {
            get {
                return ResourceManager.GetString("prompt_double", resourceCulture);
            }
        }
        
        public static string prompt_double_title {
            get {
                return ResourceManager.GetString("prompt_double_title", resourceCulture);
            }
        }
        
        public static string prompt_auto_error {
            get {
                return ResourceManager.GetString("prompt_auto_error", resourceCulture);
            }
        }
        
        public static string prompt_auto_error_title {
            get {
                return ResourceManager.GetString("prompt_auto_error_title", resourceCulture);
            }
        }
        
        public static string baggage_delete_error {
            get {
                return ResourceManager.GetString("baggage_delete_error", resourceCulture);
            }
        }
        
        public static string baggage_delete_error_title {
            get {
                return ResourceManager.GetString("baggage_delete_error_title", resourceCulture);
            }
        }
        
        public static string baggage_change_title {
            get {
                return ResourceManager.GetString("baggage_change_title", resourceCulture);
            }
        }
        
        public static string baggage_change_success {
            get {
                return ResourceManager.GetString("baggage_change_success", resourceCulture);
            }
        }
        
        public static string baggage_change_filter {
            get {
                return ResourceManager.GetString("baggage_change_filter", resourceCulture);
            }
        }
        
        public static string baggage_import_title {
            get {
                return ResourceManager.GetString("baggage_import_title", resourceCulture);
            }
        }
        
        public static string baggage_import_filter {
            get {
                return ResourceManager.GetString("baggage_import_filter", resourceCulture);
            }
        }
        
        public static string baggage_import_prompt {
            get {
                return ResourceManager.GetString("baggage_import_prompt", resourceCulture);
            }
        }
        
        public static string baggage_export_title {
            get {
                return ResourceManager.GetString("baggage_export_title", resourceCulture);
            }
        }
        
        public static string baggage_export_filter {
            get {
                return ResourceManager.GetString("baggage_export_filter", resourceCulture);
            }
        }
        
        public static string baggage_add_title {
            get {
                return ResourceManager.GetString("baggage_add_title", resourceCulture);
            }
        }

         public static string viewer_get_title {
            get {
                return ResourceManager.GetString("viewer_get_title", resourceCulture);
            }
        }
        
        public static string viewer_get_prompt {
            get {
                return ResourceManager.GetString("viewer_get_prompt", resourceCulture);
            }
        }
        
        public static string viewer_get_inactive {
            get {
                return ResourceManager.GetString("viewer_get_inactive", resourceCulture);
            }
        }
        
        public static string viewer_get_value {
            get {
                return ResourceManager.GetString("viewer_get_value", resourceCulture);
            }
        }
        
        public static string viewer_get_error {
            get {
                return ResourceManager.GetString("viewer_get_error", resourceCulture);
            }
        }
        
        public static string viewer_logger {
            get {
                return ResourceManager.GetString("viewer_logger", resourceCulture);
            }
        }
        
        public static string memcalc_para {
            get {
                return ResourceManager.GetString("memcalc_para", resourceCulture);
            }
        }
        
        public static string memcalc_union {
            get {
                return ResourceManager.GetString("memcalc_union", resourceCulture);
            }
        }
        
        public static string memcalc_title {
            get {
                return ResourceManager.GetString("memcalc_title", resourceCulture);
            }
        }
        
        public static string comref_delete {
            get {
                return ResourceManager.GetString("comref_delete", resourceCulture);
            }
        }
        
        
        public static string comref_delete_title {
            get {
                return ResourceManager.GetString("comref_delete_title", resourceCulture);
            }
        }
        
        
        public static string comref_prompt_id {
            get {
                return ResourceManager.GetString("comref_prompt_id", resourceCulture);
            }
        }
        
        public static string com_delete1 {
            get {
                return ResourceManager.GetString("com_delete1", resourceCulture);
            }
        }
        
        public static string com_delete2 {
            get {
                return ResourceManager.GetString("com_delete2", resourceCulture);
            }
        }
        
        public static string com_delete_title {
            get {
                return ResourceManager.GetString("com_delete_title", resourceCulture);
            }
        }        
        
        public static string com_prompt_id {
            get {
                return ResourceManager.GetString("com_prompt_id", resourceCulture);
            }
        }

        public static string para_delete1 {
            get {
                return ResourceManager.GetString("para_delete1", resourceCulture);
            }
        }
        
        public static string para_delete2 {
            get {
                return ResourceManager.GetString("para_delete2", resourceCulture);
            }
        }
        
        public static string para_delete_title {
            get {
                return ResourceManager.GetString("para_delete_title", resourceCulture);
            }
        }        
        
        public static string para_prompt_id {
            get {
                return ResourceManager.GetString("para_prompt_id", resourceCulture);
            }
        }
        
        public static string pararef_delete {
            get {
                return ResourceManager.GetString("pararef_delete", resourceCulture);
            }
        }
        
        public static string pararef_delete_title {
            get {
                return ResourceManager.GetString("pararef_delete_title", resourceCulture);
            }
        }        
        
        public static string pararef_prompt_id {
            get {
                return ResourceManager.GetString("pararef_prompt_id", resourceCulture);
            }
        }
        
        public static string dyn_copy_error {
            get {
                return ResourceManager.GetString("dyn_copy_error", resourceCulture);
            }
        }
        
        public static string dyn_copy_error_title {
            get {
                return ResourceManager.GetString("dyn_copy_error_title", resourceCulture);
            }
        }
        
        public static string icon_delete_error {
            get {
                return ResourceManager.GetString("icon_delete_error", resourceCulture);
            }
        }
        
        public static string icon_delete_error_title {
            get {
                return ResourceManager.GetString("icon_delete_error_title", resourceCulture);
            }
        }
        
        public static string icon_change_title {
            get {
                return ResourceManager.GetString("icon_change_title", resourceCulture);
            }
        }
        
        public static string icon_change_success {
            get {
                return ResourceManager.GetString("icon_change_success", resourceCulture);
            }
        }
        
        public static string icon_change_filter {
            get {
                return ResourceManager.GetString("icon_change_filter", resourceCulture);
            }
        }
        
        public static string icon_add_title {
            get {
                return ResourceManager.GetString("icon_add_title", resourceCulture);
            }
        }
        
        public static string icon_import_title {
            get {
                return ResourceManager.GetString("icon_import_title", resourceCulture);
            }
        }
        
        public static string icon_import_filter {
            get {
                return ResourceManager.GetString("icon_import_filter", resourceCulture);
            }
        }
        
        public static string icon_import_prompt {
            get {
                return ResourceManager.GetString("icon_import_prompt", resourceCulture);
            }
        }
        
        public static string icon_export_title {
            get {
                return ResourceManager.GetString("icon_export_title", resourceCulture);
            }
        }
        
        public static string icon_export_filter {
            get {
                return ResourceManager.GetString("icon_export_filter", resourceCulture);
            }
        }
        
        public static string prodv_no_mod {
            get {
                return ResourceManager.GetString("prodv_no_mod", resourceCulture);
            }
        }
        
        public static string checkv_not_used {
            get {
                return ResourceManager.GetString("checkv_not_used", resourceCulture);
            }
        }
        
        public static string checkv_delete {
            get {
                return ResourceManager.GetString("checkv_delete", resourceCulture);
            }
        }
        
        public static string checkv_delete_title {
            get {
                return ResourceManager.GetString("checkv_delete_title", resourceCulture);
            }
        }
        
        public static string checkv_deleted {
            get {
                return ResourceManager.GetString("checkv_deleted", resourceCulture);
            }
        }
        
        public static string checkv_warnings {
            get {
                return ResourceManager.GetString("checkv_warnings", resourceCulture);
            }
        }
        
        public static string checkv_warnings_title {
            get {
                return ResourceManager.GetString("checkv_warnings_title", resourceCulture);
            }
        }
        
        public static string checkv_started {
            get {
                return ResourceManager.GetString("checkv_started", resourceCulture);
            }
        }
        
        public static string checkv_fin {
            get {
                return ResourceManager.GetString("checkv_fin", resourceCulture);
            }
        }
        
        public static string main_def_cat {
            get {
                return ResourceManager.GetString("main_def_cat", resourceCulture);
            }
        }
        
        public static string main_empty_dpt {
            get {
                return ResourceManager.GetString("main_empty_dpt", resourceCulture);
            }
        }
        
        public static string main_add_hard_error {
            get {
                return ResourceManager.GetString("main_add_hard_error", resourceCulture);
            }
        }
        
        public static string main_add_hard_error_title {
            get {
                return ResourceManager.GetString("main_add_hard_error_title", resourceCulture);
            }
        }
        
        public static string main_lang_select {
            get {
                return ResourceManager.GetString("main_lang_select", resourceCulture);
            }
        }
        
        public static string main_lang_add_error {
            get {
                return ResourceManager.GetString("main_lang_add_error", resourceCulture);
            }
        }
        
        public static string main_project_save_title {
            get {
                return ResourceManager.GetString("main_project_save_title", resourceCulture);
            }
        }
        
        public static string main_project_filter {
            get {
                return ResourceManager.GetString("main_project_filter", resourceCulture);
            }
        }
        
        public static string main_save_template {
            get {
                return ResourceManager.GetString("main_save_template", resourceCulture);
            }
        }
        
        public static string main_save_template_title {
            get {
                return ResourceManager.GetString("main_save_template_title", resourceCulture);
            }
        }
        
        public static string main_save_template_empty {
            get {
                return ResourceManager.GetString("main_save_template_empty", resourceCulture);
            }
        }
        
        public static string main_save_template_duplicate {
            get {
                return ResourceManager.GetString("main_save_template_duplicate", resourceCulture);
            }
        }
        
        public static string main_project_open_title {
            get {
                return ResourceManager.GetString("main_project_open_title", resourceCulture);
            }
        }
        
        public static string main_project_open_format {
            get {
                return ResourceManager.GetString("main_project_open_format", resourceCulture);
            }
        }
        
        public static string main_project_open_old {
            get {
                return ResourceManager.GetString("main_project_open_old", resourceCulture);
            }
        }
        
        public static string main_project_open_new {
            get {
                return ResourceManager.GetString("main_project_open_new", resourceCulture);
            }
        }
        
        public static string main_project_open_error {
            get {
                return ResourceManager.GetString("main_project_open_error", resourceCulture);
            }
        }
        
        public static string main_project_open_error2 {
            get {
                return ResourceManager.GetString("main_project_open_error2", resourceCulture);
            }
        }
        
        public static string main_def_category {
            get {
                return ResourceManager.GetString("main_def_category", resourceCulture);
            }
        }
        
        public static string main_export_duplicate {
            get {
                return ResourceManager.GetString("main_export_duplicate", resourceCulture);
            }
        }
        
        public static string main_export_title {
            get {
                return ResourceManager.GetString("main_export_title", resourceCulture);
            }
        }
        
        public static string paratype_delete {
            get {
                return ResourceManager.GetString("paratype_delete", resourceCulture);
            }
        }
        
        public static string paratype_delete_title {
            get {
                return ResourceManager.GetString("paratype_delete_title", resourceCulture);
            }
        }
        
        public static string check_no_app {
            get {
                return ResourceManager.GetString("check_no_app", resourceCulture);
            }
        }
        
        public static string check_start {
            get {
                return ResourceManager.GetString("check_start", resourceCulture);
            }
        }
        
        public static string check_cat_sub {
            get {
                return ResourceManager.GetString("check_cat_sub", resourceCulture);
            }
        }
        
        public static string check_manu_id {
            get {
                return ResourceManager.GetString("check_manu_id", resourceCulture);
            }
        }
        
        public static string check_hard {
            get {
                return ResourceManager.GetString("check_hard", resourceCulture);
            }
        }
        
        public static string check_hard_no_physicaladdress {
            get {
                return ResourceManager.GetString("check_hard_no_physicaladdress", resourceCulture);
            }
        }
        
        public static string check_hard_no_app {
            get {
                return ResourceManager.GetString("check_hard_no_app", resourceCulture);
            }
        }
        
        public static string check_hard_no_app2 {
            get {
                return ResourceManager.GetString("check_hard_no_app2", resourceCulture);
            }
        }
        
        public static string check_app {
            get {
                return ResourceManager.GetString("check_app", resourceCulture);
            }
        }
        
        public static string check_app_openknx {
            get {
                return ResourceManager.GetString("check_app_openknx", resourceCulture);
            }
        }

        public static string check_app_number {
            get {
                return ResourceManager.GetString("check_app_number", resourceCulture);
            }
        }
        
        public static string check_baggage_no_target {
            get {
                return ResourceManager.GetString("check_baggage_no_target", resourceCulture);
            }
        }
        
        public static string check_ver {
            get {
                return ResourceManager.GetString("check_ver", resourceCulture);
            }
        }
        
        public static string check_end {
            get {
                return ResourceManager.GetString("check_end", resourceCulture);
            }
        }
        
        public static string check_ver_mediumtypes {
            get {
                return ResourceManager.GetString("check_ver_mediumtypes", resourceCulture);
            }
        }
        
        public static string check_ver_modules {
            get {
                return ResourceManager.GetString("check_ver_modules", resourceCulture);
            }
        }
        
        public static string check_ver_messages {
            get {
                return ResourceManager.GetString("check_ver_messages", resourceCulture);
            }
        }
        
        public static string check_ver_loadprod {
            get {
                return ResourceManager.GetString("check_ver_loadprod", resourceCulture);
            }
        }
        
        public static string check_ver_helptext {
            get {
                return ResourceManager.GetString("check_ver_helptext", resourceCulture);
            }
        }
        
        public static string check_ver_loadprod_size {
            get {
                return ResourceManager.GetString("check_ver_loadprod_size", resourceCulture);
            }
        }
        
        public static string check_ver_parat_name_duplicate {
            get {
                return ResourceManager.GetString("check_ver_parat_name_duplicate", resourceCulture);
            }
        }
        
        public static string check_ver_parat_size {
            get {
                return ResourceManager.GetString("check_ver_parat_size", resourceCulture);
            }
        }
        
        public static string check_ver_parat_checkbox {
            get {
                return ResourceManager.GetString("check_ver_parat_checkbox", resourceCulture);
            }
        }
        
        public static string check_ver_parat_text {
            get {
                return ResourceManager.GetString("check_ver_parat_text", resourceCulture);
            }
        }
        
        public static string check_ver_parat_enum {
            get {
                return ResourceManager.GetString("check_ver_parat_enum", resourceCulture);
            }
        }
        
        public static string check_ver_parat_enum2 {
            get {
                return ResourceManager.GetString("check_ver_parat_enum2", resourceCulture);
            }
        }
        
        public static string check_ver_parat_enum_translation {
            get {
                return ResourceManager.GetString("check_ver_parat_enum_translation", resourceCulture);
            }
        }
        
        public static string check_ver_parat_enum_icon {
            get {
                return ResourceManager.GetString("check_ver_parat_enum_icon", resourceCulture);
            }
        }
        
        public static string check_ver_parat_int_progbar {
            get {
                return ResourceManager.GetString("check_ver_parat_int_progbar", resourceCulture);
            }
        }
        
        public static string check_ver_parat_int_max {
            get {
                return ResourceManager.GetString("check_ver_parat_int_max", resourceCulture);
            }
        }
        
        public static string check_ver_parat_int_min {
            get {
                return ResourceManager.GetString("check_ver_parat_int_min", resourceCulture);
            }
        }
        
        public static string check_ver_parat_int_offset {
            get {
                return ResourceManager.GetString("check_ver_parat_int_offset", resourceCulture);
            }
        }
        
        public static string check_ver_parat_int_factor {
            get {
                return ResourceManager.GetString("check_ver_parat_int_factor", resourceCulture);
            }
        }
        
        public static string check_ver_parat_uint_min2 {
            get {
                return ResourceManager.GetString("check_ver_parat_uint_min2", resourceCulture);
            }
        }
        
        public static string check_ver_parat_int_minmax {
            get {
                return ResourceManager.GetString("check_ver_parat_int_minmax", resourceCulture);
            }
        }
        
        public static string check_ver_parat_int_max2 {
            get {
                return ResourceManager.GetString("check_ver_parat_int_max2", resourceCulture);
            }
        }
        
        public static string check_ver_parat_int_min2 {
            get {
                return ResourceManager.GetString("check_ver_parat_int_min2", resourceCulture);
            }
        }
        
        public static string check_ver_parat_float {
            get {
                return ResourceManager.GetString("check_ver_parat_float", resourceCulture);
            }
        }
        
        public static string check_ver_parat_picture {
            get {
                return ResourceManager.GetString("check_ver_parat_picture", resourceCulture);
            }
        }
        
        public static string check_ver_parat_none {
            get {
                return ResourceManager.GetString("check_ver_parat_none", resourceCulture);
            }
        }
        
        public static string check_ver_parat_color1 {
            get {
                return ResourceManager.GetString("check_ver_parat_color1", resourceCulture);
            }
        }
        
        public static string check_ver_parat_color2 {
            get {
                return ResourceManager.GetString("check_ver_parat_color2", resourceCulture);
            }
        }
        
        public static string check_ver_parat_ip1 {
            get {
                return ResourceManager.GetString("check_ver_parat_ip1", resourceCulture);
            }
        }
        
        public static string check_ver_parat_ip2 {
            get {
                return ResourceManager.GetString("check_ver_parat_ip2", resourceCulture);
            }
        }
        
        public static string check_ver_parat_date {
            get {
                return ResourceManager.GetString("check_ver_parat_date", resourceCulture);
            }
        }
        
        public static string check_ver_parat_unknown {
            get {
                return ResourceManager.GetString("check_ver_parat_unknown", resourceCulture);
            }
        }
        
        public static string check_ver_loadprod_msg {
            get {
                return ResourceManager.GetString("check_ver_loadprod_msg", resourceCulture);
            }
        }
        
        public static string check_ver_loadprod_msgref {
            get {
                return ResourceManager.GetString("check_ver_loadprod_msgref", resourceCulture);
            }
        }
        
        public static string check_ver_loadprod_msgref_error {
            get {
                return ResourceManager.GetString("check_ver_loadprod_msgref_error", resourceCulture);
            }
        }
        
        public static string check_ver_cat_number {
            get {
                return ResourceManager.GetString("check_ver_cat_number", resourceCulture);
            }
        }
        
        public static string check_ver_cat_prodnumber {
            get {
                return ResourceManager.GetString("check_ver_cat_prodnumber", resourceCulture);
            }
        }
        
        public static string check_ver_cat_hardware {
            get {
                return ResourceManager.GetString("check_ver_cat_hardware", resourceCulture);
            }
        }
        
        public static string check_ver_mod_allocs {
            get {
                return ResourceManager.GetString("check_ver_mod_allocs", resourceCulture);
            }
        }
        
        public static string check_ver_mod_paraoff {
            get {
                return ResourceManager.GetString("check_ver_mod_paraoff", resourceCulture);
            }
        }
        
        public static string check_ver_mod_combase {
            get {
                return ResourceManager.GetString("check_ver_mod_combase", resourceCulture);
            }
        }
        
        public static string check_ver_dyn_items {
            get {
                return ResourceManager.GetString("check_ver_dyn_items", resourceCulture);
            }
        }
        
        public static string check_ver_para_type {
            get {
                return ResourceManager.GetString("check_ver_para_type", resourceCulture);
            }
        }
        
        public static string check_ver_para_text {
            get {
                return ResourceManager.GetString("check_ver_para_text", resourceCulture);
            }
        }
        
        public static string check_ver_para_enum1 {
            get {
                return ResourceManager.GetString("check_ver_para_enum1", resourceCulture);
            }
        }
        
        public static string check_ver_para_enum2 {
            get {
                return ResourceManager.GetString("check_ver_para_enum2", resourceCulture);
            }
        }
        
        public static string check_ver_para_number1 {
            get {
                return ResourceManager.GetString("check_ver_para_number1", resourceCulture);
            }
        }
        
        public static string check_ver_para_number2 {
            get {
                return ResourceManager.GetString("check_ver_para_number2", resourceCulture);
            }
        }

        public static string check_ver_para_float {
            get {
                return ResourceManager.GetString("check_ver_para_float", resourceCulture);
            }
        }
        
        public static string check_ver_para_color {
            get {
                return ResourceManager.GetString("check_ver_para_color", resourceCulture);
            }
        }
        
        public static string check_ver_para_raw1 {
            get {
                return ResourceManager.GetString("check_ver_para_raw1", resourceCulture);
            }
        }
        
        public static string check_ver_para_raw2 {
            get {
                return ResourceManager.GetString("check_ver_para_raw2", resourceCulture);
            }
        }
        
        public static string check_ver_para_raw3 {
            get {
                return ResourceManager.GetString("check_ver_para_raw3", resourceCulture);
            }
        }
        
        public static string check_ver_para_date {
            get {
                return ResourceManager.GetString("check_ver_para_date", resourceCulture);
            }
        }
        
        public static string check_ver_lang_no_translation {
            get {
                return ResourceManager.GetString("check_ver_lang_no_translation", resourceCulture);
            }
        }
        
        public static string check_ver_lang_not_all {
            get {
                return ResourceManager.GetString("check_ver_lang_not_all", resourceCulture);
            }
        }
        
        public static string check_ver_lang_suffix {
            get {
                return ResourceManager.GetString("check_ver_lang_suffix", resourceCulture);
            }
        }
        
        public static string check_ver_para_save_error {
            get {
                return ResourceManager.GetString("check_ver_para_save_error", resourceCulture);
            }
        }
        
        public static string check_ver_para_save_offset {
            get {
                return ResourceManager.GetString("check_ver_para_save_offset", resourceCulture);
            }
        }
        
        public static string check_ver_para_save_offsetbit {
            get {
                return ResourceManager.GetString("check_ver_para_save_offsetbit", resourceCulture);
            }
        }
        
        public static string check_ver_para_save_obsolet {
            get {
                return ResourceManager.GetString("check_ver_para_save_obsolet", resourceCulture);
            }
        }
        
        public static string check_ver_para_save_objectindex {
            get {
                return ResourceManager.GetString("check_ver_para_save_objectindex", resourceCulture);
            }
        }
        
        public static string check_ver_para_save_propertyid {
            get {
                return ResourceManager.GetString("check_ver_para_save_propertyid", resourceCulture);
            }
        }
        
        public static string check_ver_para_save_union {
            get {
                return ResourceManager.GetString("check_ver_para_save_union", resourceCulture);
            }
        }
        
        public static string check_ver_lang_suffix_length {
            get {
                return ResourceManager.GetString("check_ver_lang_suffix_length", resourceCulture);
            }
        }
        
        public static string check_ver_pararef_no_para {
            get {
                return ResourceManager.GetString("check_ver_pararef_no_para", resourceCulture);
            }
        }

        public static string check_ver_pararef_no_display_order {
            get {
                return ResourceManager.GetString("check_ver_pararef_no_display_order", resourceCulture);
            }
        }
        
        public static string check_ver_com_not_unique {
            get {
                return ResourceManager.GetString("check_ver_com_not_unique", resourceCulture);
            }
        }
        
        public static string check_ver_com_no_dpt {
            get {
                return ResourceManager.GetString("check_ver_com_no_dpt", resourceCulture);
            }
        }
        
        public static string check_ver_com_no_dpt_ref {
            get {
                return ResourceManager.GetString("check_ver_com_no_dpt_ref", resourceCulture);
            }
        }
        
        public static string check_ver_com_no_dpst {
            get {
                return ResourceManager.GetString("check_ver_com_no_dpst", resourceCulture);
            }
        }
        
        public static string check_ver_com_no_textpara {
            get {
                return ResourceManager.GetString("check_ver_com_no_textpara", resourceCulture);
            }
        }
        
        public static string check_ver_com_no_used_textpara {
            get {
                return ResourceManager.GetString("check_ver_com_no_used_textpara", resourceCulture);
            }
        }
        
        public static string check_ver_comref_no_com {
            get {
                return ResourceManager.GetString("check_ver_comref_no_com", resourceCulture);
            }
        }
        
        public static string check_ver_mods {
            get {
                return ResourceManager.GetString("check_ver_mods", resourceCulture);
            }
        }
        
        public static string check_cat_dev_text_not_all {
            get {
                return ResourceManager.GetString("check_cat_dev_text_not_all", resourceCulture);
            }
        }
        
        public static string check_cat_dev_desc_not_all {
            get {
                return ResourceManager.GetString("check_cat_dev_desc_not_all", resourceCulture);
            }
        }
        
        public static string check_cat_cat_text_not_all {
            get {
                return ResourceManager.GetString("check_cat_cat_text_not_all", resourceCulture);
            }
        }
        
        public static string check_dyn_channel_no_number {
            get {
                return ResourceManager.GetString("check_dyn_channel_no_number", resourceCulture);
            }
        }
        
        public static string check_dyn_channel_textpara {
            get {
                return ResourceManager.GetString("check_dyn_channel_textpara", resourceCulture);
            }
        }
        
        public static string check_dyn_block_pref_error {
            get {
                return ResourceManager.GetString("check_dyn_block_pref_error", resourceCulture);
            }
        }
        
        public static string check_dyn_block_no_pref {
            get {
                return ResourceManager.GetString("check_dyn_block_no_pref", resourceCulture);
            }
        }
        
        public static string check_dyn_block_no_textpara {
            get {
                return ResourceManager.GetString("check_dyn_block_no_textpara", resourceCulture);
            }
        }
        
        public static string check_dyn_block_no_icon {
            get {
                return ResourceManager.GetString("check_dyn_block_no_icon", resourceCulture);
            }
        }
        
        public static string check_dyn_mod_no_module {
            get {
                return ResourceManager.GetString("check_dyn_mod_no_module", resourceCulture);
            }
        }
        
        public static string check_dyn_mod_empty_arg {
            get {
                return ResourceManager.GetString("check_dyn_mod_empty_arg", resourceCulture);
            }
        }
        
        public static string check_dyn_mod_no_alloc {
            get {
                return ResourceManager.GetString("check_dyn_mod_no_alloc", resourceCulture);
            }
        }
        
        public static string check_dyn_mod_alloc_error {
            get {
                return ResourceManager.GetString("check_dyn_mod_alloc_error", resourceCulture);
            }
        }
        
        public static string check_dyn_choose_no_pararef {
            get {
                return ResourceManager.GetString("check_dyn_choose_no_pararef", resourceCulture);
            }
        }
        
        public static string check_dyn_when_no_cond {
            get {
                return ResourceManager.GetString("check_dyn_when_no_cond", resourceCulture);
            }
        }
        
        public static string check_dyn_when_default {
            get {
                return ResourceManager.GetString("check_dyn_when_default", resourceCulture);
            }
        }
        
        public static string check_dyn_para_no_ref {
            get {
                return ResourceManager.GetString("check_dyn_para_no_ref", resourceCulture);
            }
        }
        
        public static string check_dyn_para_no_help {
            get {
                return ResourceManager.GetString("check_dyn_para_no_help", resourceCulture);
            }
        }
        
        public static string check_dyn_com_no_ref {
            get {
                return ResourceManager.GetString("check_dyn_com_no_ref", resourceCulture);
            }
        }
        
        public static string check_dyn_sep_no_ref {
            get {
                return ResourceManager.GetString("check_dyn_sep_no_ref", resourceCulture);
            }
        }
        
        public static string check_dyn_sep_uihint {
            get {
                return ResourceManager.GetString("check_dyn_sep_uihint", resourceCulture);
            }
        }
        
        public static string check_dyn_sep_no_icon {
            get {
                return ResourceManager.GetString("check_dyn_sep_no_icon", resourceCulture);
            }
        }
        
        public static string check_dyn_assign_no_target {
            get {
                return ResourceManager.GetString("check_dyn_assign_no_target", resourceCulture);
            }
        }
        
        public static string check_dyn_assign_no_source {
            get {
                return ResourceManager.GetString("check_dyn_assign_no_source", resourceCulture);
            }
        }
        
        public static string check_dyn_btn_no_name {
            get {
                return ResourceManager.GetString("check_dyn_btn_no_name", resourceCulture);
            }
        }
        
        public static string check_dyn_btn_no_ref {
            get {
                return ResourceManager.GetString("check_dyn_btn_no_ref", resourceCulture);
            }
        }
        
        public static string check_dyn_btn_no_icon {
            get {
                return ResourceManager.GetString("check_dyn_btn_no_icon", resourceCulture);
            }
        }
        
        public static string check_com_lang_text {
            get {
                return ResourceManager.GetString("check_com_lang_text", resourceCulture);
            }
        }
        
        public static string check_com_lang_functext {
            get {
                return ResourceManager.GetString("check_com_lang_functext", resourceCulture);
            }
        }
        
        public static string main_export_error {
            get {
                return ResourceManager.GetString("main_export_error", resourceCulture);
            }
        }
        
        public static string main_export_success {
            get {
                return ResourceManager.GetString("main_export_success", resourceCulture);
            }
        }
        
        public static string main_export_error_prod_namespace {
            get {
                return ResourceManager.GetString("main_export_error_prod_namespace", resourceCulture);
            }
        }
        
        public static string main_export_create {
            get {
                return ResourceManager.GetString("main_export_create", resourceCulture);
            }
        }
        
        public static string main_export_checked {
            get {
                return ResourceManager.GetString("main_export_checked", resourceCulture);
            }
        }
        
        public static string main_export_failed {
            get {
                return ResourceManager.GetString("main_export_failed", resourceCulture);
            }
        }
        
        public static string update_error {
            get {
                return ResourceManager.GetString("update_error", resourceCulture);
            }
        }
        
        public static string check_open_noprefix {
            get {
                return ResourceManager.GetString("check_open_noprefix", resourceCulture);
            }
        }
        
        public static string check_mod_noprefix {
            get {
                return ResourceManager.GetString("check_mod_noprefix", resourceCulture);
            }
        }
        
        public static string check_ver_union_size {
            get {
                return ResourceManager.GetString("check_ver_union_size", resourceCulture);
            }
        }

        public static string check_ver_mod_paraoff_null {
            get {
                return ResourceManager.GetString("check_ver_mod_paraoff_null", resourceCulture);
            }
        }
        
        public static string check_ver_mod_combase_null {
            get {
                return ResourceManager.GetString("check_ver_mod_combase_null", resourceCulture);
            }
        }
        
        public static string check_ver_loadprod_empty {
            get {
                return ResourceManager.GetString("check_ver_loadprod_empty", resourceCulture);
            }
        }
        
        public static string check_ver_loadprod_failed {
            get {
                return ResourceManager.GetString("check_ver_loadprod_failed", resourceCulture);
            }
        }
        
        public static string check_dyn_dr_pararef_null {
            get {
                return ResourceManager.GetString("check_dyn_dr_pararef_null", resourceCulture);
            }
        }
        
        public static string check_dyn_dr_type {
            get {
                return ResourceManager.GetString("check_dyn_dr_type", resourceCulture);
            }
        }
        
        public static string import_multiple_applications {
            get {
                return ResourceManager.GetString("import_multiple_applications", resourceCulture);
            }
        }
        
        public static string openknx_modules_duplicate {
            get {
                return ResourceManager.GetString("openknx_modules_duplicate", resourceCulture);
            }
        }
        
        public static string openknx_modules_ofm {
            get {
                return ResourceManager.GetString("openknx_modules_ofm", resourceCulture);
            }
        }
        
        public static string openknx_modules_remove {
            get {
                return ResourceManager.GetString("openknx_modules_remove", resourceCulture);
            }
        }
        
        public static string openknx_modules_title {
            get {
                return ResourceManager.GetString("openknx_modules_title", resourceCulture);
            }
        }
        
        public static string check_ver_mem_not_unique {
            get {
                return ResourceManager.GetString("check_ver_mem_not_unique", resourceCulture);
            }
        }
        
        public static string reset_bcu {
            get {
                return ResourceManager.GetString("reset_bcu", resourceCulture);
            }
        }
        
        public static string reset_bcu_title {
            get {
                return ResourceManager.GetString("reset_bcu_title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string check_ver_secure_ext_mem
        {
            get
            {
                return ResourceManager.GetString("check_ver_secure_ext_mem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string check_ver_secure_ext_prop
        {
            get
            {
                return ResourceManager.GetString("check_ver_secure_ext_prop", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string check_ver_secure_tunnel
        {
            get
            {
                return ResourceManager.GetString("check_ver_secure_tunnel", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string check_ver_secure_groups
        {
            get
            {
                return ResourceManager.GetString("check_ver_secure_groups", resourceCulture);
            }
        }
    }
}