//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaenx.Creator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaenx.Creator.Properties.Messages", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string global_exception {
            get {
                return ResourceManager.GetString("global_exception", resourceCulture);
            }
        }
        
        public static string global_exception_title {
            get {
                return ResourceManager.GetString("global_exception_title", resourceCulture);
            }
        }
        
        public static string update_new {
            get {
                return ResourceManager.GetString("update_new", resourceCulture);
            }
        }
        
        public static string update_title {
            get {
                return ResourceManager.GetString("update_title", resourceCulture);
            }
        }
        
        public static string update_uptodate {
            get {
                return ResourceManager.GetString("update_uptodate", resourceCulture);
            }
        }
        
        public static string message_prompt_id {
            get {
                return ResourceManager.GetString("message_prompt_id", resourceCulture);
            }
        }
        
        public static string prompt_id {
            get {
                return ResourceManager.GetString("prompt_id", resourceCulture);
            }
        }
        
        public static string prompt_error {
            get {
                return ResourceManager.GetString("prompt_error", resourceCulture);
            }
        }
        
        public static string prompt_error_title {
            get {
                return ResourceManager.GetString("prompt_error_title", resourceCulture);
            }
        }
        
        public static string prompt_double {
            get {
                return ResourceManager.GetString("prompt_double", resourceCulture);
            }
        }
        
        public static string prompt_double_title {
            get {
                return ResourceManager.GetString("prompt_double_title", resourceCulture);
            }
        }
        
        public static string prompt_auto_error {
            get {
                return ResourceManager.GetString("prompt_auto_error", resourceCulture);
            }
        }
        
        public static string prompt_auto_error_title {
            get {
                return ResourceManager.GetString("prompt_auto_error_title", resourceCulture);
            }
        }
        
        public static string baggage_delete_error {
            get {
                return ResourceManager.GetString("baggage_delete_error", resourceCulture);
            }
        }
        
        public static string baggage_delete_error_title {
            get {
                return ResourceManager.GetString("baggage_delete_error_title", resourceCulture);
            }
        }
        
        public static string baggage_change_title {
            get {
                return ResourceManager.GetString("baggage_change_title", resourceCulture);
            }
        }
        
        public static string baggage_change_success {
            get {
                return ResourceManager.GetString("baggage_change_success", resourceCulture);
            }
        }
        
        public static string baggage_change_filter {
            get {
                return ResourceManager.GetString("baggage_change_filter", resourceCulture);
            }
        }
        
        public static string baggage_import_title {
            get {
                return ResourceManager.GetString("baggage_import_title", resourceCulture);
            }
        }
        
        public static string baggage_import_filter {
            get {
                return ResourceManager.GetString("baggage_import_filter", resourceCulture);
            }
        }
        
        public static string baggage_import_prompt {
            get {
                return ResourceManager.GetString("baggage_import_prompt", resourceCulture);
            }
        }
        
        public static string baggage_export_title {
            get {
                return ResourceManager.GetString("baggage_export_title", resourceCulture);
            }
        }
        
        public static string baggage_export_filter {
            get {
                return ResourceManager.GetString("baggage_export_filter", resourceCulture);
            }
        }
        
        public static string viewer_get_title {
            get {
                return ResourceManager.GetString("viewer_get_title", resourceCulture);
            }
        }
        
        public static string viewer_get_prompt {
            get {
                return ResourceManager.GetString("viewer_get_prompt", resourceCulture);
            }
        }
        
        public static string viewer_get_inactive {
            get {
                return ResourceManager.GetString("viewer_get_inactive", resourceCulture);
            }
        }
        
        public static string viewer_get_value {
            get {
                return ResourceManager.GetString("viewer_get_value", resourceCulture);
            }
        }
        
        public static string viewer_get_error {
            get {
                return ResourceManager.GetString("viewer_get_error", resourceCulture);
            }
        }
        
        public static string viewer_logger {
            get {
                return ResourceManager.GetString("viewer_logger", resourceCulture);
            }
        }
        
        public static string memcalc_para {
            get {
                return ResourceManager.GetString("memcalc_para", resourceCulture);
            }
        }
        
        public static string memcalc_union {
            get {
                return ResourceManager.GetString("memcalc_union", resourceCulture);
            }
        }
        
        public static string memcalc_title {
            get {
                return ResourceManager.GetString("memcalc_title", resourceCulture);
            }
        }
        
        public static string comref_delete {
            get {
                return ResourceManager.GetString("comref_delete", resourceCulture);
            }
        }
        
        
        public static string comref_delete_title {
            get {
                return ResourceManager.GetString("comref_delete_title", resourceCulture);
            }
        }
        
        
        public static string comref_prompt_id {
            get {
                return ResourceManager.GetString("comref_prompt_id", resourceCulture);
            }
        }
        
        public static string com_delete1 {
            get {
                return ResourceManager.GetString("com_delete1", resourceCulture);
            }
        }
        
        public static string com_delete2 {
            get {
                return ResourceManager.GetString("com_delete2", resourceCulture);
            }
        }
        
        public static string com_delete_title {
            get {
                return ResourceManager.GetString("com_delete_title", resourceCulture);
            }
        }        
        
        public static string com_prompt_id {
            get {
                return ResourceManager.GetString("com_prompt_id", resourceCulture);
            }
        }

        public static string para_delete1 {
            get {
                return ResourceManager.GetString("para_delete1", resourceCulture);
            }
        }
        
        public static string para_delete2 {
            get {
                return ResourceManager.GetString("para_delete2", resourceCulture);
            }
        }
        
        public static string para_delete_title {
            get {
                return ResourceManager.GetString("para_delete_title", resourceCulture);
            }
        }        
        
        public static string para_prompt_id {
            get {
                return ResourceManager.GetString("para_prompt_id", resourceCulture);
            }
        }
        
        public static string pararef_delete {
            get {
                return ResourceManager.GetString("pararef_delete", resourceCulture);
            }
        }
        
        public static string pararef_delete_title {
            get {
                return ResourceManager.GetString("pararef_delete_title", resourceCulture);
            }
        }        
        
        public static string pararef_prompt_id {
            get {
                return ResourceManager.GetString("pararef_prompt_id", resourceCulture);
            }
        }
        
        public static string dyn_copy_error {
            get {
                return ResourceManager.GetString("dyn_copy_error", resourceCulture);
            }
        }
        
        public static string dyn_copy_error_title {
            get {
                return ResourceManager.GetString("dyn_copy_error_title", resourceCulture);
            }
        }
        
        public static string icon_delete_error {
            get {
                return ResourceManager.GetString("icon_delete_error", resourceCulture);
            }
        }
        
        public static string icon_delete_error_title {
            get {
                return ResourceManager.GetString("icon_delete_error_title", resourceCulture);
            }
        }
        
        public static string icon_change_title {
            get {
                return ResourceManager.GetString("icon_change_title", resourceCulture);
            }
        }
        
        public static string icon_change_success {
            get {
                return ResourceManager.GetString("icon_change_success", resourceCulture);
            }
        }
        
        public static string icon_change_filter {
            get {
                return ResourceManager.GetString("icon_change_filter", resourceCulture);
            }
        }
        
        public static string icon_add_title {
            get {
                return ResourceManager.GetString("icon_add_title", resourceCulture);
            }
        }
        
        public static string icon_import_title {
            get {
                return ResourceManager.GetString("icon_import_title", resourceCulture);
            }
        }
        
        public static string icon_import_filter {
            get {
                return ResourceManager.GetString("icon_import_filter", resourceCulture);
            }
        }
        
        public static string icon_import_prompt {
            get {
                return ResourceManager.GetString("icon_import_prompt", resourceCulture);
            }
        }
        
        public static string icon_export_title {
            get {
                return ResourceManager.GetString("icon_export_title", resourceCulture);
            }
        }
        
        public static string icon_export_filter {
            get {
                return ResourceManager.GetString("icon_export_filter", resourceCulture);
            }
        }
        
        public static string prodv_no_mod {
            get {
                return ResourceManager.GetString("prodv_no_mod", resourceCulture);
            }
        }
        
        public static string checkv_not_used {
            get {
                return ResourceManager.GetString("checkv_not_used", resourceCulture);
            }
        }
        
        public static string checkv_delete {
            get {
                return ResourceManager.GetString("checkv_delete", resourceCulture);
            }
        }
        
        public static string checkv_delete_title {
            get {
                return ResourceManager.GetString("checkv_delete_title", resourceCulture);
            }
        }
        
        public static string checkv_deleted {
            get {
                return ResourceManager.GetString("checkv_deleted", resourceCulture);
            }
        }
        
        public static string checkv_warnings {
            get {
                return ResourceManager.GetString("checkv_warnings", resourceCulture);
            }
        }
        
        public static string checkv_warnings_title {
            get {
                return ResourceManager.GetString("checkv_warnings_title", resourceCulture);
            }
        }
        
        public static string checkv_started {
            get {
                return ResourceManager.GetString("checkv_started", resourceCulture);
            }
        }
        
        public static string checkv_fin {
            get {
                return ResourceManager.GetString("checkv_fin", resourceCulture);
            }
        }
        
        public static string main_newets_title {
            get {
                return ResourceManager.GetString("main_newets_title", resourceCulture);
            }
        }
        
        public static string main_newets_found {
            get {
                return ResourceManager.GetString("main_newets_found", resourceCulture);
            }
        }
        
        public static string main_newets_added {
            get {
                return ResourceManager.GetString("main_newets_added", resourceCulture);
            }
        }
        
        public static string main_def_cat {
            get {
                return ResourceManager.GetString("main_def_cat", resourceCulture);
            }
        }
        
        public static string main_empty_dpt {
            get {
                return ResourceManager.GetString("main_empty_dpt", resourceCulture);
            }
        }
        
        public static string main_add_hard_error {
            get {
                return ResourceManager.GetString("main_add_hard_error", resourceCulture);
            }
        }
        
        public static string main_add_hard_error_title {
            get {
                return ResourceManager.GetString("main_add_hard_error_title", resourceCulture);
            }
        }
        
        public static string main_open_viewer {
            get {
                return ResourceManager.GetString("main_open_viewer", resourceCulture);
            }
        }
        
        public static string main_open_viewer_title {
            get {
                return ResourceManager.GetString("main_open_viewer_title", resourceCulture);
            }
        }
        
        public static string main_open_viewer_error {
            get {
                return ResourceManager.GetString("main_open_viewer_error", resourceCulture);
            }
        }
        
        public static string main_lang_select {
            get {
                return ResourceManager.GetString("main_lang_select", resourceCulture);
            }
        }
        
        public static string main_lang_add_error {
            get {
                return ResourceManager.GetString("main_lang_add_error", resourceCulture);
            }
        }
        
        public static string main_project_save_title {
            get {
                return ResourceManager.GetString("main_project_save_title", resourceCulture);
            }
        }
        
        public static string main_project_filter {
            get {
                return ResourceManager.GetString("main_project_filter", resourceCulture);
            }
        }
        
        public static string main_save_template {
            get {
                return ResourceManager.GetString("main_save_template", resourceCulture);
            }
        }
        
        public static string main_save_template_title {
            get {
                return ResourceManager.GetString("main_save_template_title", resourceCulture);
            }
        }
        
        public static string main_save_template_empty {
            get {
                return ResourceManager.GetString("main_save_template_empty", resourceCulture);
            }
        }
        
        public static string main_save_template_duplicate {
            get {
                return ResourceManager.GetString("main_save_template_duplicate", resourceCulture);
            }
        }
        
        public static string main_project_open_title {
            get {
                return ResourceManager.GetString("main_project_open_title", resourceCulture);
            }
        }
        
        public static string main_project_open_format {
            get {
                return ResourceManager.GetString("main_project_open_format", resourceCulture);
            }
        }
        
        public static string main_project_open_old {
            get {
                return ResourceManager.GetString("main_project_open_old", resourceCulture);
            }
        }
        
        public static string main_project_open_new {
            get {
                return ResourceManager.GetString("main_project_open_new", resourceCulture);
            }
        }
        
        public static string main_project_open_error {
            get {
                return ResourceManager.GetString("main_project_open_error", resourceCulture);
            }
        }
        
        public static string main_project_open_error2 {
            get {
                return ResourceManager.GetString("main_project_open_error2", resourceCulture);
            }
        }
        
        public static string main_def_category {
            get {
                return ResourceManager.GetString("main_def_category", resourceCulture);
            }
        }
        
        public static string main_export_duplicate {
            get {
                return ResourceManager.GetString("main_export_duplicate", resourceCulture);
            }
        }
        
        public static string main_export_title {
            get {
                return ResourceManager.GetString("main_export_title", resourceCulture);
            }
        }
        
    }
}