//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaenx.Creator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaenx.Creator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importieren ähnelt.
        /// </summary>
        public static string menu_impo {
            get {
                return ResourceManager.GetString("menu_impo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ETS Produktdatenbank ähnelt.
        /// </summary>
        public static string menu_impo_ets {
            get {
                return ResourceManager.GetString("menu_impo_ets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kaenx Produktdatei ähnelt.
        /// </summary>
        public static string menu_impo_kaenx {
            get {
                return ResourceManager.GetString("menu_impo_kaenx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache/Language ähnelt.
        /// </summary>
        public static string menu_lang {
            get {
                return ResourceManager.GetString("menu_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Systemeinstellung ähnelt.
        /// </summary>
        public static string menu_lang_default {
            get {
                return ResourceManager.GetString("menu_lang_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt ähnelt.
        /// </summary>
        public static string menu_proj {
            get {
                return ResourceManager.GetString("menu_proj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        public static string menu_proj_close {
            get {
                return ResourceManager.GetString("menu_proj_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu ähnelt.
        /// </summary>
        public static string menu_proj_new {
            get {
                return ResourceManager.GetString("menu_proj_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        /// </summary>
        public static string menu_proj_open {
            get {
                return ResourceManager.GetString("menu_proj_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string menu_proj_save {
            get {
                return ResourceManager.GetString("menu_proj_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applikationen ähnelt.
        /// </summary>
        public static string tabs_apps {
            get {
                return ResourceManager.GetString("tabs_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Katalog ähnelt.
        /// </summary>
        public static string tabs_cat {
            get {
                return ResourceManager.GetString("tabs_cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeins ähnelt.
        /// </summary>
        public static string tabs_gen {
            get {
                return ResourceManager.GetString("tabs_gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hardware/Geräte ähnelt.
        /// </summary>
        public static string tabs_hard {
            get {
                return ResourceManager.GetString("tabs_hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_pub {
            get {
                return ResourceManager.GetString("tabs_pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_bagg {
            get {
                return ResourceManager.GetString("tabs_bagg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string menu_impo_xml {
            get {
                return ResourceManager.GetString("menu_impo_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string menu_save_template {
            get {
                return ResourceManager.GetString("menu_save_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string menu_save_as {
            get {
                return ResourceManager.GetString("menu_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string menu_save {
            get {
                return ResourceManager.GetString("menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string menu_temp_empty {
            get {
                return ResourceManager.GetString("menu_temp_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string menu_version {
            get {
                return ResourceManager.GetString("menu_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tgen_manu {
            get {
                return ResourceManager.GetString("tgen_manu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tgen_name {
            get {
                return ResourceManager.GetString("tgen_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tgen_lang {
            get {
                return ResourceManager.GetString("tgen_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_edit {
            get {
                return ResourceManager.GetString("gen_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_add {
            get {
                return ResourceManager.GetString("gen_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_remove {
            get {
                return ResourceManager.GetString("gen_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tgen_lang_def {
            get {
                return ResourceManager.GetString("tgen_lang_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tcat_add_sub {
            get {
                return ResourceManager.GetString("tcat_add_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_name {
            get {
                return ResourceManager.GetString("prop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_number {
            get {
                return ResourceManager.GetString("prop_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tcat_iscat {
            get {
                return ResourceManager.GetString("tcat_iscat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_text {
            get {
                return ResourceManager.GetString("gen_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_lang {
            get {
                return ResourceManager.GetString("gen_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_hard {
            get {
                return ResourceManager.GetString("gen_hard", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_gen {
            get {
                return ResourceManager.GetString("gen_gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_serial {
            get {
                return ResourceManager.GetString("prop_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_vers {
            get {
                return ResourceManager.GetString("prop_vers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_buscurrent {
            get {
                return ResourceManager.GetString("prop_buscurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_haspa {
            get {
                return ResourceManager.GetString("prop_haspa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_ispower {
            get {
                return ResourceManager.GetString("prop_ispower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_iscoupler {
            get {
                return ResourceManager.GetString("prop_iscoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_ip {
            get {
                return ResourceManager.GetString("prop_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_hasapp {
            get {
                return ResourceManager.GetString("prop_hasapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_hasapp2 {
            get {
                return ResourceManager.GetString("prop_hasapp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string thard_devices {
            get {
                return ResourceManager.GetString("thard_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_ordernumber {
            get {
                return ResourceManager.GetString("prop_ordernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_isreg {
            get {
                return ResourceManager.GetString("prop_isreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_desc {
            get {
                return ResourceManager.GetString("gen_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string thard_apps {
            get {
                return ResourceManager.GetString("thard_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_import {
            get {
                return ResourceManager.GetString("gen_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_export {
            get {
                return ResourceManager.GetString("gen_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string bagg_error {
            get {
                return ResourceManager.GetString("bagg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string bagg_targetpath {
            get {
                return ResourceManager.GetString("bagg_targetpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string bagg_file {
            get {
                return ResourceManager.GetString("bagg_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string bagg_timestamp {
            get {
                return ResourceManager.GetString("bagg_timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_uid {
            get {
                return ResourceManager.GetString("gen_uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_bcu {
            get {
                return ResourceManager.GetString("prop_bcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tapps_info {
            get {
                return ResourceManager.GetString("tapps_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tapps_memory {
            get {
                return ResourceManager.GetString("tapps_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tapps_loadp {
            get {
                return ResourceManager.GetString("tapps_lodap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_copy {
            get {
                return ResourceManager.GetString("gen_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tapps_openv {
            get {
                return ResourceManager.GetString("tapps_openv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tapps_addv {
            get {
                return ResourceManager.GetString("tapps_addv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tver_addrmem {
            get {
                return ResourceManager.GetString("tver_addrmem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tver_addroff {
            get {
                return ResourceManager.GetString("tver_addroff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tver_addrmax {
            get {
                return ResourceManager.GetString("tver_addrmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tver_assomem {
            get {
                return ResourceManager.GetString("tver_assomem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tver_assooff {
            get {
                return ResourceManager.GetString("tver_assooff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tver_assomax {
            get {
                return ResourceManager.GetString("tver_assomax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tver_commem {
            get {
                return ResourceManager.GetString("tver_commem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tver_comoff {
            get {
                return ResourceManager.GetString("tver_comoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_versreplace {
            get {
                return ResourceManager.GetString("prop_versreplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_ns {
            get {
                return ResourceManager.GetString("prop_ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_langs {
            get {
                return ResourceManager.GetString("gen_langs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_check {
            get {
                return ResourceManager.GetString("tabs_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_mem {
            get {
                return ResourceManager.GetString("tabs_mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_autopara {
            get {
                return ResourceManager.GetString("vgen_autopara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_autocom {
            get {
                return ResourceManager.GetString("vgen_autocom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_union {
            get {
                return ResourceManager.GetString("vgen_union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_mods {
            get {
                return ResourceManager.GetString("vgen_mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_msg {
            get {
                return ResourceManager.GetString("vgen_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_address {
            get {
                return ResourceManager.GetString("prop_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_size {
            get {
                return ResourceManager.GetString("prop_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_autosize {
            get {
                return ResourceManager.GetString("vgen_autosize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_offset {
            get {
                return ResourceManager.GetString("prop_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_mautopara {
            get {
                return ResourceManager.GetString("vgen_mautopara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_mautoorder {
            get {
                return ResourceManager.GetString("vgen_mautoorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string vgen_heatmap {
            get {
                return ResourceManager.GetString("vgen_heatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_parat {
            get {
                return ResourceManager.GetString("tabs_parat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_union {
            get {
                return ResourceManager.GetString("tabs_union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_module {
            get {
                return ResourceManager.GetString("tabs_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_reset {
            get {
                return ResourceManager.GetString("gen_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_id {
            get {
                return ResourceManager.GetString("gen_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_paras {
            get {
                return ResourceManager.GetString("tabs_paras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_pararefs {
            get {
                return ResourceManager.GetString("tabs_pararefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_coms {
            get {
                return ResourceManager.GetString("tabs_coms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_comrefs {
            get {
                return ResourceManager.GetString("tabs_comrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_loadp {
            get {
                return ResourceManager.GetString("tabs_loadp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_dyn {
            get {
                return ResourceManager.GetString("tabs_dyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_msg {
            get {
                return ResourceManager.GetString("tabs_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tabs_arg {
            get {
                return ResourceManager.GetString("tabs_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tmod_pbo {
            get {
                return ResourceManager.GetString("tmod_pbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tmod_cbn {
            get {
                return ResourceManager.GetString("tmod_cbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string tmod_autocbn {
            get {
                return ResourceManager.GetString("tmod_autocbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string gen_filter {
            get {
                return ResourceManager.GetString("gen_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_error {
            get {
                return ResourceManager.GetString("parat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_type {
            get {
                return ResourceManager.GetString("prop_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_mansize {
            get {
                return ResourceManager.GetString("parat_mansize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_value {
            get {
                return ResourceManager.GetString("prop_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_trans {
            get {
                return ResourceManager.GetString("prop_trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_add {
            get {
                return ResourceManager.GetString("parat_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_min {
            get {
                return ResourceManager.GetString("parat_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_max {
            get {
                return ResourceManager.GetString("parat_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_increment {
            get {
                return ResourceManager.GetString("parat_increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint {
            get {
                return ResourceManager.GetString("parat_uihint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_none {
            get {
                return ResourceManager.GetString("parat_uihint_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_slider {
            get {
                return ResourceManager.GetString("parat_uihint_slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_check {
            get {
                return ResourceManager.GetString("parat_uihint_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_prog {
            get {
                return ResourceManager.GetString("parat_uihint_prog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_ha {
            get {
                return ResourceManager.GetString("parat_uihint_ha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_ga {
            get {
                return ResourceManager.GetString("parat_uihint_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_ua {
            get {
                return ResourceManager.GetString("parat_uihint_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_ba {
            get {
                return ResourceManager.GetString("parat_uihint_ba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_ma {
            get {
                return ResourceManager.GetString("parat_uihint_ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_sm {
            get {
                return ResourceManager.GetString("parat_uihint_sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_ipv4 {
            get {
                return ResourceManager.GetString("parat_uihint_ipv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_ipv6 {
            get {
                return ResourceManager.GetString("parat_uihint_ipv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_rgb {
            get {
                return ResourceManager.GetString("parat_uihint_rgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_rgbw {
            get {
                return ResourceManager.GetString("parat_uihint_rgbw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_uihint_hsv {
            get {
                return ResourceManager.GetString("parat_uihint_hsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_addrt {
            get {
                return ResourceManager.GetString("parat_addrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_vers {
            get {
                return ResourceManager.GetString("parat_vers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_bagg {
            get {
                return ResourceManager.GetString("parat_bagg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string parat_hue {
            get {
                return ResourceManager.GetString("parat_hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string uni_error {
            get {
                return ResourceManager.GetString("uni_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_sizebit {
            get {
                return ResourceManager.GetString("prop_sizebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string uni_savepath {
            get {
                return ResourceManager.GetString("uni_savepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string uni_mem {
            get {
                return ResourceManager.GetString("uni_mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_offsetbit {
            get {
                return ResourceManager.GetString("prop_offsetbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string uni_error2 {
            get {
                return ResourceManager.GetString("uni_error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string uni_addrauto {
            get {
                return ResourceManager.GetString("uni_addrauto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prodv_text {
            get {
                return ResourceManager.GetString("prodv_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prodv_settings {
            get {
                return ResourceManager.GetString("prodv_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prodv_value {
            get {
                return ResourceManager.GetString("prodv_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prodv_id {
            get {
                return ResourceManager.GetString("prodv_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prop_function {
            get {
                return ResourceManager.GetString("prop_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichen ähnelt.
        /// </summary>
        public static string prodv_getval {
            get {
                return ResourceManager.GetString("prodv_getval", resourceCulture);
            }
        }
    }
}
