using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Text;

namespace Kaenx.Creator.Models
{
    public class ParameterRef : INotifyPropertyChanged
    {

        public ParameterRef() {}
        public ParameterRef(Parameter para) {
            IsAutoGenerated = true;
            ParameterObject = para;
            Name = para.Name;
            para.PropertyChanged += Para_PropertyChanged;
        }

        private void Para_PropertyChanged(object sender, PropertyChangedEventArgs e = null) {
            if (e == null || e.PropertyName != "Name") return;
            Name = (sender as Parameter).Name;
        }

        private int _uid = -1;
        public int UId
        {
            get { return _uid; }
            set { _uid = value; Changed("UId"); }
        }

        private int _id = -1;
        public int Id
        {
            get { return _id; }
            set { _id = value; Changed("Id"); }
        }


        private string _name = "Kurze Beschreibung";
        public string Name
        {
            get { return _name; }
            set { _name = value; Changed("Name"); }
        }

        private bool _isNotUsed = false;
        [JsonIgnore]
        public bool IsNotUsed
        {
            get { return _isNotUsed; }
            set { _isNotUsed = value; Changed("IsNotUsed"); }
        }

        //TODO set false if checkbox is unchecked
        public bool IsAutoGenerated {get;set;} = false;

        private Parameter _parameterObject;
        [JsonIgnore]
        public Parameter ParameterObject
        {
            get { return _parameterObject; }
            set { 
                _parameterObject = value; 
                Changed("ParameterObject");
                if(value == null)
                    _parameterObject.PropertyChanged -= ParameterChanged;
                else
                    _parameterObject.PropertyChanged += ParameterChanged;
            }
        }

        [JsonIgnore]
        public int _parameter;
        public int Parameter
        {
            get { return ParameterObject?.UId ?? -1; }
            set { _parameter = value; }
        }


        private bool _overValue = false;
        public bool OverwriteValue
        {
            get { return _overValue; }
            set { _overValue = value; Changed("OverwriteValue"); }
        }

        private bool _overAccess = false;
        public bool OverwriteAccess
        {
            get { return _overAccess; }
            set { _overAccess = value; Changed("OverwriteAccess"); }
        }


        public ParamAccess Access { get; set; } = ParamAccess.Default;
        public string Value { get; set; } = "";
        public string Suffix { get; set; } = "";



        public ObservableCollection<Translation> Text {get;set;} = new ObservableCollection<Translation>();
        private bool _transText = false;
        public bool TranslationText
        {
            get { return _transText; }
            set { _transText = value; Changed("TranslationText"); }
        }
        private bool _overText = false;
        public bool OverwriteText
        {
            get { return _overText; }
            set { _overText = value; Changed("OverwriteText"); }
        }


        public event PropertyChangedEventHandler PropertyChanged;
        private void Changed(string name)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }

        private void ParameterChanged(object sender, PropertyChangedEventArgs e)
        {
            if(!IsAutoGenerated || e.PropertyName != "Name") return;
            Name = ParameterObject.Name;
        }
    }
}
